### ISSUE TITLE
faster, slimmer, lighter

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-html-tools#130]
Firefox says we download 519KB on an empty cache:

* 7 js files totalling 279,99KB
* 4 css files totalling 179,29KB
* 1 html file totalling 40,47KB
* 4 images totalling 18,72KB

It's not too bad (half the size of google.com!), but still about as large [as one of the lesser Russian classics](http://idlewords.com/talks/website_obesity.htm). And we are after all just serving text.

Possible ideas:
* Is it possible to trim bootstrap down to only what we use? Or exchange it for something both smaller and nicer?
* Should we try using something smaller-but-equivalent like [jquip](https://github.com/mythz/jquip) instead of jquery? 
* Are there parts of our own js that is not used, that we can cut out?

More ideas:
http://www.lightentheweb.com/

**Comment by share-with-me** [comment]
> Is it possible to trim bootstrap down to only what we use? Or exchange it for something both smaller and nicer?

> Are there parts of our own js that is not used, that we can cut out?

IMO, we could start with these 2 ideas. We can make use of JS code coverage tool for instance,

**Comment by share-with-me** [comment]
> Is it possible to trim bootstrap down to only what we use? Or exchange it for something both smaller and nicer?

> Are there parts of our own js that is not used, that we can cut out?

We can definitely start with these. A JS code coverage tool such as [JSCover](http://tntim96.github.io/JSCover/) is a tool that displays a summary of the code coverage and an example for the same is [here](http://tntim96.github.io/JSCover/example-report-yui3/jscoverage.html?test/index.html).

**Comment by sushain97** [comment]
There are existing tools out there that are excellent at tree shaking. However, it would complicate the build process and require extra dependencies: https://webpack.js.org/guides/tree-shaking/.

Personally, I would be all for switching to a more context appropriate build process :) We could always create a branch/releases that have a compiled ready-to-execute version of the site.

**Comment by unhammer** [comment]
Hm, when I said "cut out" I wasn't thinking of doing this at compile time, but rather actually cutting out the code that we don't use from the *source* – dead code belongs in branches :)

**Comment by sushain97** [comment]
I agree that dead code belongs in branches. However, I haven't checked
carefully but I would venture that very little of our JS is dead. ESLint
errors on lots of potential causes and I'm usually relatively careful with
it. I think the majority of what we serve is e.g. jQuery, that we couldn't
really cut down manually.

Manually trimming Bootstrap would make it really tricky to upgrade
versions. I haven't seen a suitable replacement for Bootstrap either. The
community and documentation are hard to match.

I don't think the jQuery alternative would work since Bootstrap depends on
jQuery. We could switch to something like Vue but I don't know if that
would yield an improvement. It would also require a near complete rewrite
(would be better in the long run but would take lots of effort).

On Jun 4, 2017 12:06 PM, "Kevin Brubeck Unhammer" <notifications@github.com>
wrote:

Hm, when I said "cut out" I wasn't thinking of doing this at compile time,
but rather actually cutting out the code that we don't use from the *source*
– dead code belongs in branches :)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/goavki/apertium-html-tools/issues/130#issuecomment-306060204>,
or mute the thread

**Comment by unhammer** [comment]
> Manually trimming Bootstrap would make it really tricky to upgrade
> versions. I haven't seen a suitable replacement for Bootstrap either. The
> community and documentation are hard to match.
>
> I don't think the jQuery alternative would work since Bootstrap depends on
> jQuery. We could switch to something like Vue but I don't know if that
> would yield an improvement. It would also require a near complete rewrite
> (would be better in the long run but would take lots of effort).

Ah, didn't think of that dependency; yeah, that makes what I was thinking of more difficult.

**Comment by Androbin** [comment]
I ran the coverage report tool in Chrome DevTools for first load:
- 83.9 % ~ 109 kb of `css/min.css` are not used
- 58.1 % ~ 66 kb of `js/min.js` are not used
- 74.1 % ~ 47 kb of `piwik/piwik.js` are not used

Some of this could of course be used in various places. But it would be nice to be able to load that on demand and most importantly: after the initial page load.

I will try to split these into smaller packages, at least in `initial` and `additional`.

**Comment by Androbin** [comment]
> If we want to do something like only include analysis js code when `ANALYSIS_ENABLED=1`, then I think we should first solve #80

@unhammer @sushain97 You think we can split on a per-module basis now?

**Comment by Androbin** [comment]
It seems like `css/min.css` are `js/min.js` aren't actually minified at all.
Basic minification would already yield:
- a 25.6 % ~ 33.35 kb reduction of `css/min.css`
- a 43.2 % ~ 48.77 kb reduction of `js/min.js`

This should be fairly easy to implement.

**Comment by sushain97** [comment]
Keep in mind that we should *not* be editing any vendored CSS/JS. That
probably means not editing 95% of the code (why this issue has been stale
for a while).

On Dec 20, 2017 11:14 AM, "Robin Richtsfeld" <notifications@github.com>
wrote:

I ran the coverage report tool in Chrome DevTools for first load:

   - 83.9 % ~ 109 kb of css/min.css are not used
   - 58.1 % ~ 66 kb of js/min.js are not used
   - 74.1 % ~ 47 kb of piwik/piwik.js are not used

Some of this could of course be used in various places. But it would be
nice to be able to load that on demand and most importantly: after the
initial page load.

I will try to split these into smaller packages, at least in initial and
additional.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/goavki/apertium-html-tools/issues/130#issuecomment-353125147>,
or mute the thread

**Comment by Androbin** [comment]
Currently, `css/min.css` and `js/min.js` are [not minified](https://github.com/goavki/apertium-html-tools/issues/130#issuecomment-353128033) like their supposed to be.
I propose to add a minification step to `Makefile` similar to [this gist](https://gist.github.com/rgrove/1116056).

**Comment by sushain97** [comment]
That would introduce a Java dependency, unfortunately.

**Comment by Androbin** [comment]
> That would introduce a Java dependency, unfortunately.

What about using `uglifyjs` instead?
* https://gist.github.com/bpierre/1341808
* https://gist.github.com/gabekneisley/2655106

**Comment by sushain97** [comment]
If I understand correctly, that would be a Node dependency.

**Comment by Androbin** [comment]
> If I understand correctly, that would be a Node dependency.

Wouldn't that be doable?

**Comment by sushain97** [comment]
It's the same problem as a Java dependency.

**Comment by Androbin** [comment]
@sushain97 In which language would a minification step need to be written to be acceptable?
Or else we could just do some dirty processing using regular expressions.

**Comment by sushain97** [comment]
Bash or Python. However, anything too complex is likely to have edge cases
we miss and/or be unmaintainable.

**Comment by Androbin** [comment]
A naive implementation would probably just strip whitespace (and the like) in very obvious cases. Any somewhat more sophisticated implementation is expected to be robust.
I'll try the former and then look around for the latter.

**Comment by Androbin** [comment]
#243 already got us https://github.com/goavki/apertium-html-tools/issues/130#issuecomment-353128033.

Actually, JS and CSS aren't our main problem anymore:
![after-chart](https://user-images.githubusercontent.com/16437156/34464897-3f32b57a-ee95-11e7-8ef9-719d279c99e6.png)
![after-table](https://user-images.githubusercontent.com/16437156/34464907-e645c550-ee95-11e7-87dd-b99695e0aa12.png)

Note: These number refer to the initial page load on an empty cache.

**Comment by Androbin** [comment]
Also, https://github.com/goavki/apertium-html-tools/issues/130#issuecomment-353125147 still holds for the most part.

- 84.3 % ~ 89 kb of `css/min.css` are not used
- 57.7 % ~ 45 kb of `js/min.js` are not used

Note: These numbers refer to the initial page load. But we want to defer loading the rest.

**Comment by Androbin** [comment]
We currently load `https://fonts.googleapis.com/css?family=Ubuntu` (amongst others).
But most of that font family is not actually needed. We want to load a subset of it.

**Comment by Androbin** [comment]
This could reduce our font footprint by a 2.5-fold.

**Comment by sushain97** [comment]
What are you proposing removing? Don't forget that we need to support at least Aragonese (arg), Avar (ava), Catalan (cat), English (eng), Basque (eus), French (fra), German (deu), Hebrew (heb), Karakalpak (kaa), Kazakh (kaz), Kyrgyz (kir), Nynorsk Norwegian (nno), Bokmål Norwegian (nob), Occitan (oci), Portuguese (por), Romanian (ron), Saami (sme), Spanish (spa), Tatar (tat), Thai (tha), Turkish (tur), Uzbek (uzb), Uyghur (uig), and Chinese (zho).

**Comment by sushain97** [comment]
Adding https://github.com/purifycss/purifycss to the CSS minification pipeline would save a large % of the CSS bytes. Switching to Bootstrap 4 would also reduce our needs to jQuery slim which would save a bunch of bytes.

**Comment by Androbin** [comment]
`purifycss` offers a `--min` flag. Shall we "add" `purifycss` to the CSS pipeline or use it as a replacement?

**Comment by sushain97** [comment]
Replacement works.

**Comment by Androbin** [comment]
I guess this should still be done on a per-file basis, though `purifycss` tends to merging.

**Comment by Androbin** [comment]
Should this still be done on a per-file basis or do we want `purifycss` to produce `all.css` directly?

**Comment by sushain97** [comment]
I don't think there's a reason to produce intermediate files.

On Mar 7, 2018 2:02 PM, "Robin Richtsfeld" <notifications@github.com> wrote:

Should this still be done on a per-file basis or do we want purifycss to
produce all.css directly?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/apertium/apertium-html-tools/issues/130#issuecomment-371265974>,
or mute the thread

**Comment by Androbin** [comment]
Just noticed that the minification step is performed on the merged file anyway.

**Comment by Androbin** [comment]
> If we want to do something like only include analysis js code when `ANALYSIS_ENABLED=1`, then I think we should first solve #80

@unhammer @sushain97 You think we should try splitting on a per-module basis now?

**Comment by sushain97** [comment]
I'm a bit concerned that would complicate the build more than it would actually save. Our non-vendored JS size is quite small.

**Comment by sushain97** [comment]
On `master`, we now send ~260K gzipped on the wire for `beta.apertium.org` (note that we actually embed some images and CSS in the JS). I think we'd be quite hard pressed to make this any smaller. If we had a version of Boostrap that used CSS modules and we could shake our unused CSS, I could see us dropping ~10K. Other than that, I doubt there's low-hanging fruit. In that light, closing this issue unless we have any new ideas :)

![image](https://user-images.githubusercontent.com/4211838/117563775-fa6f2580-b05c-11eb-9a4f-2f1102be72db.png)

**Comment by Androbin** [comment]
Low-hanging fruit one:
```html
<link rel="preconnect" href="https://fonts.gstatic.com">
```

Low-hanging fruit two:
![](https://user-images.githubusercontent.com/16437156/117953840-b9a23580-b316-11eb-941d-6d07d2da2e37.png)

**Comment by sushain97** [comment]
apertium.org is not running master. Try out beta.apertium.org.
