### ISSUE TITLE
Translation help string is outdated (only refers to text translation)

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-html-tools#198]
Currently website translation uses the same "translate your text" string as for text translation.  This should be a new string to the effect of "translate a website", which should be integrated into the string localisation system.  Also, might we consider adding a "(beta)" string too?

**Comment by sushain97** [comment]
> Currently website translation uses the same "translate your text" string as for text translation. This should be a new string to the effect of "translate a website", which should be integrated into the string localisation system.

I agree with the problem but I think a slightly different solution is in order. If I understand correctly, the text you're referring to is currently (in English):

> Choose two languages and translate your text using Apertium's translation platform!

In fact, this is **already inaccurate** since we offer document translation. I propose switching it to:

> Choose two languages and translate using Apertium's translation platform!

Such a modification would be more future-proof and cover both website, document and text translation. Since this is a change in the existing string (`Translation_Help`) I propose the following solution:

1) Fix the English string.
2) Document on this ticket which languages are now **outdated** for this string and adjust this ticket as they are fixed. (checkboxes)

> Also, might we consider adding a "(beta)" string too?

I'm not sold on this one since most of what we do is roughly beta anyway ;)

**Comment by jonorthwash** [comment]
> I propose switching it to:
> > Choose two languages and translate using Apertium's translation platform!

The problem with this is that "translate" will require an object in a lot of languages, which forces you back into saying what you're translating.

> I'm not sold on this one since most of what we do is roughly beta anyway ;)

Yeah, but website translation is less likely to work right than most of the rest of the website.  It might be good to alert people to this one way or the other, so they don't get their hopes up or get confused and click "translate" a hundred times when it doesn't work.

**Comment by sushain97** [comment]
> The problem with this is that "translate" will require an object in a lot of languages, which forces you back into saying what you're translating.

Good point. I guess in that case they would have to specify [text, documents and websites], some vague object or use an alternate construction. I don't think we should be switching that tagline as users switch between interfaces so it needs to be general.

> It might be good to alert people to this one way or the other, so they don't get their hopes up or get confused and click "translate" a hundred times when it doesn't work.

Since we display "Translation not available" upon failure, I don't think this would be a problem? I think the larger concern I have with a beta label is that removing it from all the localizations may be non-trivial. We did include an "experimental" qualifier with enabling pivot languages. I'm comfortable with it there since I don't see us (ever?) removing it.

**Comment by sushain97** [comment]
cc @share-with-me

**Comment by jonorthwash** [comment]
> I guess in that case they would have to specify [text, documents and websites], some vague object or use an alternate construction. I don't think we should be switching that tagline as users switch between interfaces so it needs to be general.

E.g., "translate your material" would be okay, at least as an option for other languages.

> Since we display "Translation not available" upon failure, I don't think this would be a problem?

Unless it just screws stuff up because of issues with the html of the page?

> I think the larger concern I have with a beta label is that removing it from all the localizations may be non-trivial.

I was imagining a separate string for that.

> We did include an "experimental" qualifier with enabling pivot languages. I'm comfortable with it there since I don't see us (ever?) removing it.

Yeah, that's a permanently experimental feature :D

**Comment by sushain97** [comment]
> E.g., "translate your material" would be okay, at least as an option for other languages.

:+1:

> Unless it just screws stuff up because of issues with the html of the page?

Fair.

> I was imagining a separate string for that. Removing it from the interface would be trivial.

Sounds good! We can have a "Beta" badge.

**Comment by share-with-me** [comment]
Um, so for the text on website translation interface, what should I change it to? (Sorry but couldn't infer the exact string and the position of Beta tag :/)

**Comment by sushain97** [comment]
@share-with-me the string is just "Beta" and the tag position isn't determined yet.

**Comment by share-with-me** [comment]
Oh, so should I replace the entire `Choose two languages and translate your text using Apertium's translation platform!` and replace it with just `Beta` ?

**Comment by sushain97** [comment]
No, the "Beta" is just a badge we should add somewhere. I would suggest not focusing on this ticket for now.

**Comment by share-with-me** [comment]
Ohh! In that case, I have updated both the front as well as the backend PRs. Please have a look :)

**Comment by sushain97** [comment]
This is no longer valid after #269.
