### ISSUE TITLE
Upgrade to Bootstrap 4

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-html-tools#200]
https://getbootstrap.com/

**Comment by efeichen** [comment]
I would like to work on this issue, is there anything I should be careful about when implementing BS4 that you can think of?

**Comment by sushain97** [comment]
There's a lot of inline styling we do that can be replaced with BS4 utility classes (for a start). All the themes need to be tested as well :) I believe Bootswatch has updated theirs. Nothing else comes to mind immediately.

One would hope this isn't too many large changes! Also note that this might not actually be possible if Bootstrap beta is buggy and we *might* not merge it until BS4 goes past beta depending on how much is different.

**Comment by myfrom** [comment]
Hello!
Could I take this as part of a GCI Task (as well as #314 since it's related)?
I'd like to make sure it still needs to be worked on and that no-one has taken this already.

Also, could I ask a few questions:
- As far as I understand, the only required thing with the upgrade is to preserve current look of the website, right?
- And what are the build tools used in this project? Could it be extended with SASS compiler? Because it's the easiest way to theme Bootstrap 4 AFAIK.

**Comment by sushain97** [comment]
Sure!

> As far as I understand, the only required thing with the upgrade is to preserve current look of the website, right?

Yes and replace any redundant classes that exist in BS4.

> And what are the build tools used in this project? Could it be extended with SASS compiler? Because it's the easiest way to theme Bootstrap 4 AFAIK.

We don't use Node/Ruby/C in this project so adding the SASS compiler is a no-go. However, the themed version could be built using the SASS compiler and then used in the repo. Note that this project already supports some notion of theming from bootswatch.com via the `make [theme]` target.

**Comment by sushain97** [comment]
https://github.com/apertium/apertium-html-tools/pull/355

**Comment by MaathavanJkr** [comment]
#356
