### ISSUE TITLE
Can't download translated documents in Safari on iOS

### ISSUE THREAD

**Issue by myfrom** [apertium/apertium-html-tools#222]
**How to reproduce?**
Translate any document on Safari on iOS and click the "Download _filename_" link.

**Expected behaviour**
The file downloads.

**Actual behavior**
The file opens as plain text in the browser tab.

**Affected browsers**
Safari on iOS

**Comment by diogoscf** [comment]
Apple only allows downloads for files from the Internet since iOS10 (this isn’t just Safari since all browsers on iOS are basically Safari with a different interface, due to Apple Rules). The download only works however, if the link to the file ends with a supported file extension, but html-tools doesn’t seem to do that. Also, the only way to download stuff on iOS, even with `download` in `a` is using the share button.

**Comment by sushain97** [comment]
Interesting... how hard would it be to fix?

**Comment by diogoscf** [comment]
The link to the document would have to have the correct extension and it would still open as plain text in the browser, but you would be able to download it using the share button. Apple really hasn’t made a good job with downloads from iOS Safari.

**Comment by omairqazi** [comment]
Because of Apple rules, this is not allowed. But you can try using any download manager from app store.

**Comment by diogoscf** [comment]
I'm not sure when exactly this was implemented, but downloading documents, including the ones translated by html-tools, works in the latest versions of iOS/iPadOS.

**Comment by myfrom** [comment]
It's supported since iOS 13, I believe
