### ISSUE TITLE
Display deprecation notice more conservatively

### ISSUE THREAD

**Issue by flammie** [apertium/apertium-html-tools#325]
When I open apertium.org I get a warning that I'm using old browser (Chromium 63), is this generated by the apertium website? If it's tunablem and not needed by some feature used in the code, it might be nicer turned off or so, I think atm 63 cannot be more than couple of months old and it's not really the task of apertium.org to remind me of browser updates...

**Comment by sushain97** [comment]
> I think atm 63 cannot be more than couple of months old
63 is about 9 months old and IIRC anything older than ~3 versions is considered 'deprecated' since they push for frequent updates. In fact, it's 'almost' considered insecure: https://github.com/browser-update/browser-update/blob/master/browsers.json#L24

> is this generated by the apertium website?
They're from http://browser-update.org/.

> If it's tunable
The thresholds can be configured. I don't think the current settings are an issue since you can dismiss it once and never get it again.

> not needed by some feature used in the code
This codebase doesn't use any transpilation step so it's not easy to tell what the exact browser requirements are. Personally, I'd be happy to switch to ES6 and use `babel-preset-env` and feed those settings into the notification.

**Comment by sushain97** [comment]
> If apertium.org provides broken experience for users of few month old versions of browsers there's something that needs to be fixed.

Is it broken for you? It shouldn't be.

**Comment by flammie** [comment]
I must admit I just don't understand modern web technology enough so I trust your judgement that the warning is well justified :-D

**Comment by sushain97** [comment]
Alas, if we were using more modern web technology, we wouldn't have this problem since we could downlevel the code and polyfill according to exactly what requirements we wanted to set instead of trying to guess very conservatively.

**Comment by sushain97** [comment]
There is no longer a browser update notice!
