### ISSUE TITLE
website broken with latest palemoon browser

### ISSUE THREAD

**Issue by rofl0r** [apertium/apertium-html-tools#417]
website is completely blank, js console reveals

```
SyntaxError: expected expression, got '?'[Learn More]
in index.js: return(e=e?e.displayName||e.name:"")
```

some web developer to eager to use latest JS features?

**Comment by mr-martian** [comment]
What I find puzzling is that the error appears to be objecting to the ternary operator, which, according to https://caniuse.com/?search=ternary has been supported by just about everything for nearly a decade.

**Comment by TinoDidriksen** [comment]
That's not what it's objecting to. The actual error is regarding `checked:r??e._wrapperState.initialChecked` which uses [??](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) which is a much newer feature that's only been in browsers since Jan 2020: https://caniuse.com/?search=coalescing

I would agree that's too new. Everything else we do supports ~5 years old distros, so our website should too. IE11 is still out under that criteria, which is the important part.

**Comment by rofl0r** [comment]
thanks!

**Comment by TinoDidriksen** [comment]
Fixed and live on https://beta.apertium.org/

**Comment by rofl0r** [comment]
works, ty!
