### ISSUE TITLE
there's a hamburger menu on apertium.org mobile version

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-html-tools#451]
![image](https://user-images.githubusercontent.com/56868/174457018-e2b96033-3d56-48d4-8fb2-7ca69fdaf2e7.png)
that doesn't actually expand or do anything when you click it

**Comment by sushain97** [comment]
Wow, I thought this would be a super easy fix and it ended up being quite a mess since a lot of the navbar styles were saddled with confusing absolute positioning styles from the old html-tools. Should be fixed as of https://github.com/apertium/apertium-html-tools/pull/452. Let me know if there are still issues.
